import { PrairieDog } from '../types/PrairieDog';

const mockPrairieDogs: PrairieDog[] = [
    // Original prairie dogs with updated dates
    {
        id: '1',
        name: 'Whiskers',
        location: { lat: 43.8041, lng: -111.8237 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 12,
        story: "Whiskers leads a small colony near Idaho Falls. The harsh winter winds make it difficult for his family to gather food safely.",
        familySize: 6,
        colonyName: "Rocky Ridge Colony",
        weatherImpact: "The freezing temperatures force the colony to spend extra energy staying warm instead of maintaining their burrow system."
    },
    {
        id: '2',
        name: 'Scout',
        location: { lat: 40.7608, lng: -104.8214 },
        sweaterSize: 'XS',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 15,
        story: "Scout is a young mother who recently established a new burrow. The cold snap has made it challenging to keep her pups warm.",
        familySize: 4,
        colonyName: "Prairie View Colony",
        weatherImpact: "The young pups are particularly vulnerable to the cold, requiring Scout to spend more time in the burrow and less time foraging."
    },
    // Additional prairie dogs across more states
    {
        id: '6',
        name: 'Maple',
        location: { lat: 44.9778, lng: -93.2650 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 2,
        story: "Maple's colony in Minnesota faces extreme cold challenges. She's developed innovative burrowing techniques to create warmer spaces.",
        familySize: 9,
        colonyName: "Twin Cities Burrow",
        weatherImpact: "The deep freeze has forced the colony to create multiple emergency warm chambers."
    },
    {
        id: '7',
        name: 'Rocky',
        location: { lat: 41.5868, lng: -93.6250 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 8,
        story: "Rocky leads Iowa's largest prairie dog family. Their extensive tunnel network is struggling against the frozen ground.",
        familySize: 12,
        colonyName: "Des Moines Meadows",
        weatherImpact: "Frozen soil has made expanding their tunnel system nearly impossible, limiting food storage capabilities."
    },
    {
        id: '8',
        name: 'Storm',
        location: { lat: 39.7817, lng: -89.6501 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 11,
        story: "Storm's Illinois colony discovered their winter food cache is freezing, requiring urgent adaptation strategies.",
        familySize: 7,
        colonyName: "Springfield Plains",
        weatherImpact: "Food preservation has become a critical challenge as temperature fluctuations cause freeze-thaw cycles."
    },
    {
        id: '9',
        name: 'Willow',
        location: { lat: 38.9072, lng: -77.0369 },
        sweaterSize: 'XS',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 18,
        story: "Willow's family near DC has been impacted by urban development, making winter survival even more challenging.",
        familySize: 5,
        colonyName: "Capital Meadow",
        weatherImpact: "Limited natural shelter options due to development have increased cold weather vulnerability."
    },
    {
        id: '10',
        name: 'Thunder',
        location: { lat: 35.0844, lng: -106.6504 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 20,
        story: "Thunder's New Mexico colony faces unusual cold snaps, disrupting their normal winter preparation routines.",
        familySize: 8,
        colonyName: "Desert Vista",
        weatherImpact: "Unexpected temperature drops have caught the colony off-guard, depleting energy reserves."
    },
    {
        id: '11',
        name: 'Echo',
        location: { lat: 47.7511, lng: -120.7401 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 25,
        story: "Echo's Washington state colony has found their usual food sources buried under unexpected snowfall.",
        familySize: 6,
        colonyName: "Cascade Meadows",
        weatherImpact: "Snow coverage has significantly reduced access to winter forage areas."
    },
    {
        id: '12',
        name: 'Shadow',
        location: { lat: 46.5891, lng: -112.0391 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 10,
        story: "Shadow's Montana family is teaching younger members new survival techniques for the intensifying winters.",
        familySize: 10,
        colonyName: "Helena Hills",
        weatherImpact: "Traditional winter survival knowledge needs updating for more extreme conditions."
    },
    {
        id: '13',
        name: 'River',
        location: { lat: 44.9778, lng: -89.6301 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 4,
        story: "River's Wisconsin colony is struggling with frozen water sources, impacting their daily routines.",
        familySize: 7,
        colonyName: "Wausau Warren",
        weatherImpact: "Limited access to water has forced changes in foraging patterns and social behaviors."
    },
    {
        id: '14',
        name: 'Phoenix',
        location: { lat: 39.7392, lng: -104.9903 },
        sweaterSize: 'XS',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 16,
        story: "Phoenix's Denver colony faces urban challenges combined with severe temperature drops.",
        familySize: 5,
        colonyName: "Mile High Burrow",
        weatherImpact: "Urban heat islands create confusing temperature patterns affecting winter preparation."
    },
    {
        id: '15',
        name: 'Aurora',
        location: { lat: 43.0731, lng: -107.2903 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 9,
        story: "Aurora's family discovered their winter food storage is running low due to extended cold periods requiring more caloric intake.",
        familySize: 6,
        colonyName: "Central Wyoming Warren",
        weatherImpact: "Increased energy needs for warmth are depleting food stores faster than anticipated."
    },
    {
        id: '16',
        name: 'Frost',
        location: { lat: 42.3601, lng: -71.0589 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 14,
        story: "Frost's colony near Boston has adapted to urban life, but the cold winter is making their usual routines challenging.",
        familySize: 4,
        colonyName: "Urban Edge Colony",
        weatherImpact: "City life provides some shelter, but also creates unique challenges during cold snaps."
    },
    {
        id: '17',
        name: 'Bear',
        location: { lat: 45.5155, lng: -122.6789 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 22,
        story: "Bear leads a Portland colony facing unusual weather patterns that disrupt their traditional winter behavior.",
        familySize: 9,
        colonyName: "Rose City Burrow",
        weatherImpact: "Unpredictable weather swings are causing confusion in the colony's seasonal adaptations."
    },
    {
        id: '18',
        name: 'Misty',
        location: { lat: 39.9612, lng: -82.9988 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 13,
        story: "Misty's Ohio colony is experimenting with new burrow insulation techniques using local materials.",
        familySize: 7,
        colonyName: "Columbus Commons",
        weatherImpact: "Traditional burrow designs are proving insufficient for the intensifying winter cold."
    },
    {
        id: '19',
        name: 'Summit',
        location: { lat: 40.2338, lng: -111.6585 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 17,
        story: "Summit's Utah colony found their high-altitude location especially challenging this winter.",
        familySize: 5,
        colonyName: "Mountain Vista Colony",
        weatherImpact: "Higher elevation combined with cold fronts creates dangerous windchill conditions."
    },
    {
        id: '20',
        name: 'Prairie',
        location: { lat: 41.1399, lng: -104.8202 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 11,
        story: "Prairie's Cheyenne colony is teaching the younger generation new techniques for snow tunneling.",
        familySize: 8,
        colonyName: "High Plains Haven",
        weatherImpact: "Deep snow cover requires innovative approaches to maintaining colony connections."
    },
    {
        id: '21',
        name: 'Creek',
        location: { lat: 38.8339, lng: -104.8214 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 19,
        story: "Creek's colony has developed a sophisticated relay system to share warmth in their burrow network.",
        familySize: 6,
        colonyName: "Springs Settlement",
        weatherImpact: "Cooperative warming strategies are essential for the colony's survival."
    },
    {
        id: '22',
        name: 'Dawn',
        location: { lat: 42.8864, lng: -112.4458 },
        sweaterSize: 'XS',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 10,
        story: "Dawn's Pocatello colony faces challenges with frozen ground affecting their food storage chambers.",
        familySize: 5,
        colonyName: "Gateway Colony",
        weatherImpact: "Permafrost conditions are compromising traditional food preservation methods."
    },
    {
        id: '23',
        name: 'Alpine',
        location: { lat: 45.6916, lng: -111.0389 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 6,
        story: "Alpine's Bozeman colony has innovated by creating wind-protected corridors between burrow entrances.",
        familySize: 7,
        colonyName: "Gallatin Valley Group",
        weatherImpact: "Strategic tunnel planning helps minimize exposure during necessary above-ground activities."
    },
    {
        id: '24',
        name: 'Vale',
        location: { lat: 43.9783, lng: -116.9934 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 16,
        story: "Vale leads a colony that's teaching others how to identify and utilize natural windbreaks in the landscape.",
        familySize: 6,
        colonyName: "Western Plains Colony",
        weatherImpact: "Knowledge sharing about natural shelter has become crucial for winter survival."
    },
    {
        id: '25',
        name: 'Brook',
        location: { lat: 42.3601, lng: -108.7829 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 12,
        story: "Brook's colony has started creating emergency food caches in strategic locations throughout their territory.",
        familySize: 8,
        colonyName: "Red Desert Warren",
        weatherImpact: "Distributed food storage provides backup when main chambers become inaccessible due to ice."
    },
    {
        id: '3',
        name: 'Sage',
        location: { lat: 46.8797, lng: -100.7832 },
        sweaterSize: 'M',
        needsSweater: true,
        lastSeenDate: '2025-01-14',
        temperature: 5,
        story: "Sage is the eldest member of his colony, teaching younger prairie dogs survival techniques. The extreme cold makes it harder for him to move quickly.",
        familySize: 8,
        colonyName: "Bismarck Meadows Colony",
        weatherImpact: "The entire colony relies on Sage's experience, but the cold weather has limited his ability to demonstrate crucial foraging patterns."
    },
    {
        id: '4',
        name: 'Luna',
        location: { lat: 41.8781, lng: -107.2380 },
        sweaterSize: 'S',
        needsSweater: true,
        lastSeenDate: '2025-01-16',
        temperature: 8,
        story: "Luna discovered a new food source for her colony, but accessing it requires crossing exposed areas in the bitter wind.",
        familySize: 5,
        colonyName: "Wind River Colony",
        weatherImpact: "The colony's food security is at risk as the cold makes their usual foraging routes too dangerous."
    },
    {
        id: '5',
        name: 'Dusty',
        location: { lat: 44.5133, lng: -103.2052 },
        sweaterSize: 'L',
        needsSweater: true,
        lastSeenDate: '2025-01-15',
        temperature: 7,
        story: "Dusty is responsible for maintaining the colony's alarm system, but the cold has made his warning calls less effective as members stay deeper in their burrows.",
        familySize: 7,
        colonyName: "Black Hills Colony",
        weatherImpact: "The colony's communication network is strained as the cold forces them to spend less time above ground."
    }
    // Additional prairie dogs can be added here to reach 25 total
];

export const getPrairieDogs = (): Promise<PrairieDog[]> => {
    return Promise.resolve(mockPrairieDogs);
};
